[package]
name = "my_library"
version = "0.0.3"

[addresses]
StarcoinFramework = "0x1"
MyAddr = "0xa0F6D12997A611f4a7CcBd093B745ed7"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="cf1deda180af40a8b3e26c0c7b548c4c290cd7e7"}