[package]
name = "addr_aggregator"
version = "0.0.1"

[addresses]
StarcoinFramework = "0x1"
MyAddr = "0x1168e88ffc5cec53b398b42d61885bbb"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="9ea61ce1429070c945002b26ef5f5ea6b72884e4"}